### ISSUE TITLE
BigQuery fails in SQL Service

### ISSUE THREAD

**Issue by konstjar** [OHDSI/ArachneExecutionEngine#402]
The `OAuthAccessToken` is not passed in connection string

```
2024-10-09 11:30:14.766  INFO 21 --- [nio-8888-exec-6] c.o.a.e.execution.sql.SQLService         : Execution [1041959256] started in SQL Service
2024-10-09 11:30:14.766  INFO 21 --- [sTaskExecutor-1] c.o.a.e.s.i.HikariConnectionPoolService  : Using JDBC: jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=xxxxxx;OAuthType=0;OAuthServiceAcctEmail=yyyyy@xxxxx.iam.gserviceaccount.com;Timeout=1000;useQueryCache=0
2024-10-09 11:30:14.766  INFO 21 --- [nio-8888-exec-6] c.o.a.e.api.v1.AnalysisController        : Request [1041959256] of type [SQL] accepted into processing
2024-10-09 11:30:14.767  INFO 21 --- [sTaskExecutor-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-21 - Starting...
2024-10-09 11:30:15.771 ERROR 21 --- [sTaskExecutor-1] com.zaxxer.hikari.pool.HikariPool        : HikariPool-21 - Exception during pool initialization.

java.sql.SQLNonTransientConnectionException: [Simba][JDBC](10100) Connection Refused: [Simba][JDBC](11640) Required Connection Key(s): OAuthPvtKeyPath; [Simba][JDBC](11480) Optional Connection Key(s): AdditionalProjects, AllowLargeResults, DefaultDataset, EnableHighThroughPutAPI, FetchThreadsPerResultSet, ForceHTAPI, HighThroughPutMinTableSize, IgnoreTransactions, KMSKeyName, Language, LargeResultDataset, LargeResultsDatasetExpirationTime, LargeResultTable, MaxResults, OAuthAccessToken, OAuthClientId, OAuthClientSecret, OAuthRefreshToken, ProxyHost, RequestGoogleDriveScope, StringColumnLength, TimestampFallback
        at com.simba.googlebigquery.exceptions.ExceptionConverter.toSQLException(Unknown Source) ~[google-cloud-bigquery-1.2.15.jar!/:na]
        at com.simba.googlebigquery.jdbc.common.BaseConnectionFactory.checkResponseMap(Unknown Source) ~[google-cloud-bigquery-1.2.15.jar!/:na]
        at com.simba.googlebigquery.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source) ~[google-cloud-bigquery-1.2.15.jar!/:na]
        at com.simba.googlebigquery.jdbc.common.AbstractDriver.connect(Unknown Source) ~[google-cloud-bigquery-1.2.15.jar!/:na]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117) ~[HikariCP-2.7.2.jar!/:na]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123) ~[HikariCP-2.7.2.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375) ~[HikariCP-2.7.2.jar!/:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204) ~[HikariCP-2.7.2.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445) [HikariCP-2.7.2.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516) [HikariCP-2.7.2.jar!/:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116) [HikariCP-2.7.2.jar!/:na]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) [HikariCP-2.7.2.jar!/:na]
        at com.odysseusinc.arachne.executionengine.service.impl.HikariConnectionPoolService.buildDataSource(HikariConnectionPoolService.java:71) [classes!/:2.4-DEV-SNAPSHOT]
        at com.odysseusinc.arachne.executionengine.service.impl.HikariConnectionPoolService.lambda$getDataSource$1(HikariConnectionPoolService.java:53) [classes!/:2.4-DEV-SNAPSHOT]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4904) ~[guava-20.0.jar!/:na]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628) ~[guava-20.0.jar!/:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336) ~[guava-20.0.jar!/:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295) ~[guava-20.0.jar!/:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208) ~[guava-20.0.jar!/:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4053) ~[guava-20.0.jar!/:na]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4899) ~[guava-20.0.jar!/:na]
        at com.odysseusinc.arachne.executionengine.service.impl.HikariConnectionPoolService.getDataSource(HikariConnectionPoolService.java:52) [classes!/:2.4-DEV-SNAPSHOT]
        at com.odysseusinc.arachne.executionengine.execution.sql.SQLService.lambda$analyze$1(SQLService.java:101) ~[classes!/:2.4-DEV-SNAPSHOT]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[na:1.8.0_422]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_422]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_422]
        at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_422]

2024-10-09 11:30:15.773 ERROR 21 --- [sTaskExecutor-1] c.o.a.e.service.CdmMetadataService       : Failed to detect CDM Version, [Simba][JDBC](10100) Connection Refused: [Simba][JDBC](11640) Required Connection Key(s): OAuthPvtKeyPath; [Simba][JDBC](11480) Optional Connection Key(s): AdditionalProjects, AllowLargeResults, DefaultDataset, EnableHighThroughPutAPI, FetchThreadsPerResultSet, ForceHTAPI, HighThroughPutMinTableSize, IgnoreTransactions, KMSKeyName, Language, LargeResultDataset, LargeResultsDatasetExpirationTime, LargeResultTable, MaxResults, OAuthAccessToken, OAuthClientId, OAuthClientSecret, OAuthRefreshToken, ProxyHost, RequestGoogleDriveScope, StringColumnLength, TimestampFallback
2024-10-09 11:30:15.774 ERROR 21 --- [sTaskExecutor-1] c.o.a.e.service.CdmMetadataService       : Failed to get metadata, [Simba][JDBC](10100) Connection Refused: [Simba][JDBC](11640) Required Connection Key(s): OAuthPvtKeyPath; [Simba][JDBC](11480) Optional Connection Key(s): AdditionalProjects, AllowLargeResults, DefaultDataset, EnableHighThroughPutAPI, FetchThreadsPerResultSet, ForceHTAPI, HighThroughPutMinTableSize, IgnoreTransactions, KMSKeyName, Language, LargeResultDataset, LargeResultsDatasetExpirationTime, LargeResultTable, MaxResults, OAuthAccessToken, OAuthClientId, OAuthClientSecret, OAuthRefreshToken, ProxyHost, RequestGoogleDriveScope, StringColumnLength, TimestampFallback
2024-10-09 11:30:15.774  INFO 21 --- [sTaskExecutor-1] c.o.a.e.execution.AnalysisService        : Execution [1041959256] completed, sending results...
2024-10-09 11:30:15.775  INFO 21 --- [sTaskExecutor-1] c.o.a.e.execution.CallbackService        : Execution [1041959256] produced 9 result files
2024-10-09 11:30:15.775  INFO 21 --- [sTaskExecutor-1] c.o.a.e.execution.CallbackService        : Adding folder [/etc/executions/exec-8112107845325859420] to zip [/tmp/1728473415774-0/1041959256_result.zip] with chunk size = 10485760
2024-10-09 11:30:15.777  WARN 21 --- [sTaskExecutor-1] c.o.a.e.execution.CallbackService        : Execution [1041959256] send result: EXECUTE - Error: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: [Simba][JDBC](10100) Connection Refused: [Simba][JDBC](11640) Required Connection Key(s): OAuthPvtKeyPath; [Simba][JDBC](11480) Optional Connection Key(s): AdditionalProjects, AllowLargeResults, DefaultDataset, EnableHighThroughPutAPI, FetchThreadsPerResultSet, ForceHTAPI, HighThroughPutMinTableSize, IgnoreTransactions, KMSKeyName, Language, LargeResultDataset, LargeResultsDatasetExpirationTime, LargeResultTable, MaxResults, OAuthAccessToken, OAuthClientId, OAuthClientSecret, OAuthRefreshToken, ProxyHost, RequestGoogleDriveScope, StringColumnLength, TimestampFallback
2024-10-09 11:30:15.932  INFO 21 --- [sTaskExecutor-1] c.o.a.e.execution.CallbackService        : Execution [1041959256] result status sent, response HTTP 200 OK
```

**Comment by konstjar** [comment]
Tested and confirmed working.
